---
title: "ologit test"
output: html_notebook
---

Based on https://stats.oarc.ucla.edu/r/dae/ordinal-logistic-regression/

```{r}
require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)
```

```{r}
dat <- read.dta("https://stats.idre.ucla.edu/stat/data/ologit.dta")
head(dat)
```
```{r}
lapply(dat[, c("apply", "pared", "public")], table)
```
```{r}
ftable(xtabs(~ public + apply + pared, data=dat))
```
```{r}
ggplot(dat, aes(x=apply, y=gpa)) + 
  geom_boxplot(size=.75) +
  #geom_jitter(alpha = .5) +
  facet_grid(pared ~ public, margins = TRUE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust =1))
```
```{r}
m <- polr(apply ~ pared + public + gpa, data = dat, Hess=TRUE)
summary(m)
```
```{r}
## store coefficients to calculate p value
(ctable <- coef(summary(m)))
```
```{r}
# Get degrees of freedom (approximated)
n <- nrow(dat)
k <- length(m$coefficients)
df <- n - k

# convert t-values to z-values
z_values <- ctable[, "t value"] * sqrt(df / (df -1))

# calculate p values
p <- pnorm(abs(ctable[, "t value"]), lower.tail=FALSE) * 2
p_z <- pnorm(abs(z_values), lower.tail=FALSE) * 2

## combined table
ctable <- cbind(ctable, "p value" = p)
(ctable <- cbind(ctable, "p value (from z)" = p_z))
```



